package com.icannhas.readysaster;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOCATION_DETAILS.
 */
public class LocationDetails {

    private Long id;
    private Double lat;
    private Double lng;
    private String photoFile;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LocationDetails() {
    }

    public LocationDetails(Long id) {
        this.id = id;
    }

    public LocationDetails(Long id, Double lat, Double lng, String photoFile) {
        this.id = id;
        this.lat = lat;
        this.lng = lng;
        this.photoFile = photoFile;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public String getPhotoFile() {
        return photoFile;
    }

    public void setPhotoFile(String photoFile) {
        this.photoFile = photoFile;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
