package com.icannhas.readysaster;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOCATION.
 */
public class Location {

    private Long id;
    private Double lat;
    private Double lng;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, Double lat, Double lng) {
        this.id = id;
        this.lat = lat;
        this.lng = lng;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
